### Import Library

In [1]:
import cv2
import numpy as np

### Read image with Open Cv

In [15]:
citra = cv2.imread('image/logo.png')

### Show image

In [16]:
cv2.imshow("citra asli", citra)
cv2.waitKey() 
cv2.destroyAllWindows()

### Image dimension & data type

In [6]:
print(citra.shape)
print(citra.dtype)

(128, 128, 3)
uint8


### Split RGB image

In [7]:
b = citra[:,:,0]
g = citra[:,:,1]
r = citra[:,:,2]

### Convert RGB to grayscale

In [8]:
panjang = len(citra)
lebar = len(citra[0])

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j]

citra_gray = citra_gray.astype(np.uint8)

In [9]:
cv2.imshow("ABU", citra_gray)
cv2.waitKey() 
cv2.destroyAllWindows()

In [10]:
print(citra_gray)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Convert Grayscale to Binary

In [11]:
panjang = len(citra)
lebar = len(citra[0])

ambang = 210

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
          citra_biner[i,j] = 0
        else:
          citra_biner[i,j] = 1

In [12]:
cv2.imshow("biner", citra_biner)
cv2.waitKey() 
cv2.destroyAllWindows()

### Print pixel on specific index

In [13]:
print(citra_gray[50,50])

166


In [14]:
print(citra_biner[50,50])

1.0
